language: php
sudo: false
php:
  - 5.5

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

script: phpunit --configuration .phpunit.xml

notifications:
  email: true

install:
    - composer require seld/jsonlint:1.3.1
